name: Build Docker

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Build image for"
        required: true
        default: "linux/amd64"
        type: choice
        options:
          - linux/amd64
          - linux/arm64
      tag:
        description: "Override image tag"
        required: false
        type: string

env:
  IMAGE_NAME: corplink_rs
  PROXY_IMAGE_NAME: corplink_proxy

jobs:
  build-docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Metadata
        id: meta
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          PROXY_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$PROXY_IMAGE_NAME
          PROXY_IMAGE_ID=$(echo $PROXY_IMAGE_ID | tr '[A-Z]' '[a-z]')
          PLATFORM="linux/amd64"
          [ -n "${{ github.event.inputs.platform }}" ] && PLATFORM="${{ github.event.inputs.platform }}"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          [ -n "${{ github.event.inputs.tag }}" ] && VERSION="${{ github.event.inputs.tag }}"
          echo "image=$IMAGE_ID" >> $GITHUB_OUTPUT
          echo "proxy_image=$PROXY_IMAGE_ID" >> $GITHUB_OUTPUT
          echo "platform=$PLATFORM" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and Upload
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}
          labels: runnumber=${{ github.run_id }}
          provenance: false
          platforms: ${{ steps.meta.outputs.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Upload Image with Proxy
        id: docker_build_proxy_image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.proxy
          push: true
          tags: ${{ steps.meta.outputs.proxy_image }}:${{ steps.meta.outputs.version }}
          labels: runnumber=${{ github.run_id }}
          provenance: false
          platforms: ${{ steps.meta.outputs.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
